---
id: 6733bee844600f35c05b8264
title: try...catch...finally 是如何工作的？
challengeType: 11
videoId: _3whfUfxGYI
dashedName: how-does-try-catch-finally-work
---

# --description--

观看视频或阅读文字稿，并回答下方的问题。

# --transcript--

`try…catch…finally` 是如何工作的？

在上一节课的视频中，你学习了如何在程序中抛出异常。在本节课的视频中，我们将学习如何在 `try…catch…finally` 代码块中优雅地处理这些错误。

`try` 代码块用于包裹可能会抛出错误的代码。它就像一个安全区，用于尝试可能失败的操作。

`catch` 代码块用于捕获并处理在 `try` 代码块中发生的错误。你可以在 `catch` 中使用 `Error` 对象来检查出错的原因。

`finally` 代码块会在 `try` 和 `catch` 代码块之后执行，无论是否发生了错误。它通常用于清理任务，比如关闭文件或释放资源。

下面是一个使用 `try…catch` 代码块的例子：

```js
function processInput(input) {
  if (typeof input !== "string") {
    throw new TypeError("Input must be a string.");
  }

  return input.toUpperCase();
}

try {
  console.log("Starting to process input...");
  const result = processInput(9);
  console.log("Processed result:", result);
} catch (error) {
  console.error("Error occurred:", error.message);
} 
```

在这个例子中，我们有一个名为 `processInput` 的函数，它首先检查 `input` 是否不是字符串类型。如果是这样，就抛出一个错误。否则，返回 `input` 的大写形式。

我们在 `try` 代码块中调用该函数。由于函数调用抛出了错误，所以会被 `catch` 代码块捕获，并在控制台显示错误信息。

传递给 `catch` 代码块的错误是一个 `Error` 对象，其中包含有关该错误的信息。在这里，我们使用 `message` 属性向用户显示可读的信息。

我们使用 `console.error`，因为它专门用于记录错误。在许多现代浏览器中，`console.error()` 的输出会以红色显示在控制台中。

`finally` 语句无论是否抛出异常都会执行。

```js
try {
  // 可能抛出错误的代码
} catch (error) {
  // 处理错误的代码
} finally {
  // 无论是否发生错误都会执行的代码
}
```

`finally` 语句的一个很好的用例是处理文件时。在 JavaScript 中，你可以打开一个文件，用 `try` 代码块写入数据。如果出现任何错误，可以用 `catch` 捕获这些错误。然后用 `finally` 语句关闭文件。

# --questions--

## --text--

`try` 代码块的最佳描述是什么？

## --answers--

它用于在发生错误后自动重新运行代码。

### --feedback--

想一想 `try…catch…finally` 语句中各个代码块的顺序，以及每个代码块处理的任务类型。

---

它用于处理错误。

### --feedback--

想一想 `try…catch…finally` 语句中各个代码块的顺序，以及每个代码块处理的任务类型。

---

它用于在抛出错误前进行设置。

### --feedback--

想一想 `try…catch…finally` 语句中各个代码块的顺序，以及每个代码块处理的任务类型。

---

它是用于包裹可能抛出错误代码的安全区。

## --video-solution--

4

## --text--

哪一个代码块即使发生错误也总会执行？

## --answers--

`try`

### --feedback--

这个代码块通常用于清理任务。

---

`catch`

### --feedback--

这个代码块通常用于清理任务。

---

`finally`

---

`throw`

### --feedback--

这个代码块通常用于清理任务。

## --video-solution--

3

## --text--

`catch` 代码块的作用是什么？

## --answers--

执行可能抛出错误的代码。

### --feedback--

当 `try` 代码块中出现问题时，这个代码块会被激活。

---

定义一个安全的代码执行空间。

### --feedback--

当 `try` 代码块中出现问题时，这个代码块会被激活。

---

优雅地处理错误，防止程序崩溃。

---

无论是否发生错误都执行。

### --feedback--

当 `try` 代码块中出现问题时，这个代码块会被激活。

## --video-solution--

3

